### ISSUE TITLE
Google Mapがきちんと表示されない

### ISSUE THREAD

**Issue by e165728** [East6/Board-Logger#16]
<img width="1280" alt="2018-11-13 18 05 17" src="https://user-images.githubusercontent.com/23465260/48403177-b42cfa00-e770-11e8-998a-ad3a6525f101.png">

ローカルでは動くけどヘロクにあげると画像のような表示がされる．．．

**Comment by himajin315** [comment]
Herokuに環境変数はsetしましたか？

**Comment by himajin315** [comment]
<img width="919" alt="2018-11-13 19 30 14" src="https://user-images.githubusercontent.com/1221303/48407636-a3818180-e77a-11e8-981b-2f9742e81492.png">

**Comment by himajin315** [comment]
no-api-keys, invalid-key とあるので、APIキーが登録されてなさそうですね。

**Comment by himajin315** [comment]
原因はこれですね。
<img width="668" alt="2018-11-13 19 53 30" src="https://user-images.githubusercontent.com/1221303/48408916-d8430800-e77d-11e8-943c-3e9a40409636.png">

**Comment by hogehiga** [comment]
アプリが更新され、API Keyが表示されているのは確認したんですが、今度は
`ReferenceError: MarkerClusterer is not defined`というエラーが出て地図が表示されませんでした(Firefoxの開発ツールのコンソールにて確認)。
