### ISSUE TITLE
ユーザーの認可機能について

### ISSUE THREAD

**Issue by e165719** [East6/Board-Logger#21]
ユーザーが他ユーザーに自分のボードを共有したいと思っています。

はじめに，ユーザーページ(app/views/boards/index.html.erb)にアクセス制限を設け，とりあえず全てのボードを共有しようとしています。
次の段階として，各ボード(app/views/boards/show.html.erb)にアクセス制限を設けようとしています。

今，ユーザーページにアクセス制限を設けようとしているのですが，リダイレクトによるURLの制限はできているのですが，直接の制限をするためにはどうしたらいいですか？？

プルリクを出しておくので確認お願いします。

**Comment by e165719** [comment]
確認ありがとうございます。

「Aさんが，Aさんの作ったボードを見ることができる人を指定できる」のように作りたいと考えています。

![img_4721](https://user-images.githubusercontent.com/23465228/48658302-e4331080-ea82-11e8-85b4-078efeb2d90c.jpg)

AさんがBさんからボードを見る許可が出ていない場合，AさんがBさんのページにいくと，
上記の図の目標のようにBさんのページのところで "許可がありません" のような表示を出したかったのですが

現在の状況のようにBさんのページにいけないようにする, という方法でもいいのでしょうか。

エラーを確認しました。ありがとうございます。

**Comment by hogehiga** [comment]
> 「Aさんが，Aさんの作ったボードを見ることができる人を指定できる」のように作りたいと考えています。

なるほど。 せっかくなんでこの図はTrelloの対応するプロダクトバックログに貼っておくと、他のメンバーが確認できるので良いと思います。

> 上記の図の目標のようにBさんのページのところで "許可がありません" のような表示を出したかったのですが
> 現在の状況のようにBさんのページにいけないようにする, という方法でもいいのでしょうか。

BさんがAさんに許可を出していない状況で、AさんがBさんについてどれくらいのことを知ることができるか？によります。 

例えば、AさんにはBさんの存在すら知らせない場合は、現在の実装のようにリダイレクトでいいと思います(この場合は、フレンド申請？は例えばNintendo Switchのフレンドコード(<https://www.nintendo.co.jp/support/switch/friends/index.html>)のように実装する手も考えられます)。
ただ、この状況でもAさんはBさんについてある程度のことは知ることができるなら、Bさんのページへ行けるようにして、例えば「Bさんのボード一覧は見られるけど詳細(show.html.erb)は見られない」などとする、というのも考えられます(詳細まで見られると、知らない人にエントリーの仕方？まで知られてアレな感じがします。)。


まあTrelloやSlackを見てると、リダイレクトでいいと思いますが、そのへんは相談して決めるといいと思います。
