### ISSUE TITLE
プルダウン方式でデータを入力したが表示が上手くされない。前までできていました。

### ISSUE THREAD

**Issue by Kumaharu** [East6/Board-Logger#26]
[https://github.com/East6/Board-Logger/blob/master/app/views/boards/show.html.erb](url)

`<% @wave.each do |wave| %>
          <tr>
            <td><%= wave.status %></td>
            <td><%= wave.windway %></td>
            <td><%= wave.shore %></td>
            <td><%= wave.windpower %></td>
            <td><%= wave.swell %></td>
            <td><%= wave.swellway %></td>
            <td><%= wave.comment %></td>
          </tr>
        <% end %>
      </table>
    
    <%= form_for @newWave, :url => wave_create_path do |f| %>
      <div class="form-horizontal">
        <%=f.label "サイズ"%>
        <%=f.select:status, [["",""],["腰","腰"],["腹","腹"],["胸","胸"],["頭","頭"],["頭オーバー","頭オーバー"]] %>
        <%= f.label "うねりの大きさ" %>
        <%=f.select:swell, [["",""],["~0.1","~0.1"],["~1.5","~1.5"],["~2.0","~2.0"],["~2.5","~2.5"],["~3.0","~3.0"]] %>
        <%= f.label "うねりの向き" %>
        <%=f.select:swellway, [["",""],["北","北"],["北東","北東"],["東","東"],["南東","南東"],["南","南"],["南西","南西"],["西","西"],["北西","北西"]] %>
        <%= f.label "風向き" %>
        <%=f.select:windway, [["",""],["北","北"],["北東","北東"],["東","東"],["南東","南東"],["南","南"],["南西","南西"],["西","西"],["北西","北西"]] %>
        <%=f.label "何ショア？"%>
        <%=f.select:shore, [["",""],["オフショア","オフショア"],["サイドオフ","サイドオフ"],["サイドオン","サイドオン"],["オンショア","オンショア"]] %>
        <%=f.label "風の強さ"%>
        <%=f.select:windpower, [["",""],["~2.0","~2.0"],["~4.0","~4.0"],["~6.0","~6.0"],["~8.0","~8.0"]] %>
        <%= f.label "コメント" %>
        <%= f.text_field :comment, class: "form-control mb-2 mr-sm-2", placeholder: "コメント"%>
        <%= f.hidden_field :board_id %>
        <%= f.submit "投稿" , class: "btn btn-primary mb-2 btn-lg"%>
      </div>
    <% end 

> 

> %>`

**Comment by hogehiga** [comment]
どのブランチで動かないのかわからんので、とりあえずmasterで試そうと思ってmasterを手元に持ってきたところ、

    -> % bin/rails db:migrate
    rails aborted!
    ActiveRecord::DuplicateMigrationNameError:

    Multiple migrations have the name AddInfosToWaves.

となり、migrateができませんでした(つまり、アプリが起動しない。ということはHerokuへmasterをpushすると、それは動かなくなるはず)。

私以外の環境でも、masterをcloneしてきて再現するなら、まずこれの解消からするとよいかと思われます。

**Comment by Kumaharu** [comment]
これは、同じ内容のmigrateファイルが２つある問題だと思います。ブランチでは１つmigrateファイルを消去して解消したのですが、これが良いものか疑問です。

**Comment by hogehiga** [comment]
コミット f5430e3ce13a7fd282fde9d5841aae66194b9ed3 でこの現象が発生するようになってます。

参考: https://github.com/East6/Board-Logger/pull/25#discussion_r234067240

**Comment by hogehiga** [comment]
> ブランチでは１つmigrateファイルを消去して解消したのですが、これが良いものか疑問です。

うーん、いいと思うんですが……
とりあえずこれをデプロイしてherokuでdb:migrateする前に、dbのバックアップをとっておくと、何かあってもなんとかなると思います。

参考: https://devcenter.heroku.com/articles/heroku-postgres-backups#creating-a-backup

**Comment by Kumaharu** [comment]
heroku pg:backups:capture --app herokuのアップ名　　で良いんですか？
このアプリは、データベースは１つですよね。

branchでmigrationファイル消して動いたものをmergeするって方法はどうでしょうか？

**Comment by Kumaharu** [comment]
とりあえず、ローカルのmasterで動くようにしたので、masterにあげました。表示が上手く行かない問題はまだ解決できていません。

**Comment by hogehiga** [comment]
> heroku pg:backups:capture --app herokuのアップ名　　で良いんですか？

はい。

> このアプリは、データベースは１つですよね。

はい。


> branchでmigrationファイル消して動いたものをmergeするって方法はどうでしょうか？

herokuにデプロイしてdb:migrateするためにはそれでいいんですけど、今回はmigrationが(一時的にせよ)ちょっと怪しい状態になっているので、念のためにデータをバックアップしたほうがいいということです。

**Comment by hogehiga** [comment]
> とりあえず、ローカルのmasterで動くようにしたので、masterにあげました。表示が上手く行かない問題はまだ解決できていません。

自分の手元ではhimajinさんの変更(<https://github.com/East6/Board-Logger/pull/25#discussion_r234067240>)を入れると表示できましたけど……

**Comment by Kumaharu** [comment]
すみません。変更ミスを見つけました。
問題解決しました。ありがとうございました。
