### ISSUE TITLE
タイムゾーンの変更が出来ません。

### ISSUE THREAD

**Issue by Kumaharu** [East6/Board-Logger#34]
日付を表示したが、UTCの時間になっていて日本時間とずれている。
タイムゾーンの設定をしてみたが、上手く行かなかった。これはcreated_at がdatatime型で
タイムゾーンを保持できないためだと考えている。

`		     config.time_zone = 'Asia/Tokyo'
     
     config.active_record.default_timezone:local

     config.active_record.time_zone_aware_attributes:true

`

gitのbranch URL
https://github.com/East6/Board-Logger/commit/a046ebbb0fec10b6dd6827fd874dc77ea559c3da

**Comment by himajin315** [comment]
アプリ側とサーバ側の時間を確認すると良いかも 🤔 
https://qiita.com/Horie1024/items/85688099707610f70fa6

**Comment by Kumaharu** [comment]
+9とか出ますが一応日本時間出力できました。
