### ISSUE TITLE
削除機能の挙動がおかしいので困ってます。

### ISSUE THREAD

**Issue by ta-ryo** [East6/Board-Logger#43]
ユーザーのもつボードの削除でエラーが出ます。
原因と解説をしてくれると,とても嬉しいです。
一応自分で調べてみて、多対多のモデル間での削除エラーと書かれていましたが上手く解決出来ませんでした。
<img width="1280" alt="screen shot 2018-11-20 at 15 13 56" src="https://user-images.githubusercontent.com/23465165/48755003-248acc80-ecd7-11e8-8cb1-2e6003d20eeb.png">

**Comment by ta-ryo** [comment]
すいません。自力解決出来ました。
理由としては結びつけたいボードと中身の情報とのhas_manyが書かれておらず関連付けが出来ていない状況でした。

**Comment by himajin315** [comment]
自力で解決できてよかった 👏
