### ISSUE TITLE
今いる位置情報をGPSなどを用いて取得したいのですが、何をしていいか途方に暮れています。

### ISSUE THREAD

**Issue by Kumaharu** [East6/Board-Logger#47]

**Comment by hogehiga** [comment]
やったことないですが、この辺読めばなんとかなりそうです。

https://developer.mozilla.org/ja/docs/Web/API/Geolocation/Using_geolocation

**Comment by hogehiga** [comment]
Safariというのがどれかよくわかりませんが、私の手元のMac OS Xで動いているSafari(バージョン11.1.2 (13605.3.8))では、設定を適切に行えば位置情報を取得できました。
設定は[システム環境設定]-[セキュリティとプライバシー]-[プライバシー]-[位置情報サービス]から行えました。

**Comment by hogehiga** [comment]
取得に使ったのは <https://developer.mozilla.org/ja/docs/Web/API/Geolocation/Using_geolocation#Geolocation_Live_Example>です。

**Comment by hogehiga** [comment]
しかし、Safariだと「位置情報を送信するために設定を見直しなさい」みたいなことすら言わないのでアレな感じではあります。

**Comment by Kumaharu** [comment]
safariの設定で位置情報をonにしましたが動きません。。。

<img width="347" alt="2018-11-23 22 16 11" src="https://user-images.githubusercontent.com/23465282/48945441-b1e74e80-ef6d-11e8-8ee2-9f6f1e1b7654.png">

branch
https://github.com/East6/Board-Logger/commit/7942928ece5e00376711c445f8d4e9d74419fa6b

**Comment by hogehiga** [comment]
あと、このアプリで <https://github.com/East6/Board-Logger/issues/47#issuecomment-441145127> の状態を再現するための操作がわからないので教えてください。

**Comment by hogehiga** [comment]
あっ、「Show my location」ボタンを見落としてました、すみません。

**Comment by hogehiga** [comment]
コンソールによると、

<img width="590" alt="2018-11-24 2 40 02" src="https://user-images.githubusercontent.com/6975731/48955832-11a42080-ef93-11e8-92b1-3c4eab7e85ed.png">

とのことなんでHTTPSにすればいいんじゃないでしょうか。
というよりFirefoxがHTTPで取れるのがだいぶおかしい気がする……

**Comment by hogehiga** [comment]
PumaをHTTPSでアクセスできるようにしたら、Safariでこのアプリを開き、Show my locationボタンを押したときに、緯度と経度らしきものが出ました。

そもそも、MDNのマニュアル(<https://developer.mozilla.org/ja/docs/Web/API/Geolocation/Using_geolocation>)に堂々と目立つ形で「This feature is available only in secure contexts (HTTPS), in some or all supporting browsers.」と書いてあるんで、気づかんかったこっちが悪いですね。

**Comment by Kumaharu** [comment]
herokuでやったところ動きました！
