### ISSUE TITLE
デモの後、@himajinさんにお話したバグについての問題です。

### ISSUE THREAD

**Issue by Kumaharu** [East6/Board-Logger#55]
波情報を選択式入力するところで、”サイズ”の入力をしないとそれ以外の”ウネリ”の向きや”風の向き”が表示されないです。

コード部は　show.html.erbと
https://github.com/East6/Board-Logger/blob/master/app/views/boards/show.html.erb
wave_controller.rb
https://github.com/East6/Board-Logger/blob/master/app/controllers/wave_controller.rb

**Comment by himajin315** [comment]
status に blankが入らないような設定なってるからです。
https://github.com/East6/Board-Logger/blob/master/app/models/wave.rb#L3

**Comment by Kumaharu** [comment]
バリデーションをコメントアウトしたところ治りました。
