### ISSUE TITLE
JavaScriptで宣言した変数をhtml.erbで扱いたいときは何を使えばいいですか。

### ISSUE THREAD

**Issue by ta-ryo** [East6/Board-Logger#58]

**Comment by ta-ryo** [comment]
ブランチ名はGPSでshow.html.erbとGPS.jsでGPS.jsの中の変数 latitude とlongitudeを使いたいです。

**Comment by hogehiga** [comment]
扱うというのがよくわからんのですが、例えば`$("#output_area").html(latitude)`などではどうですかね？

**Comment by hogehiga** [comment]
あー、erb 内。。。


無理ですね。

**Comment by hogehiga** [comment]
JSの結果をもう一度サーバーに送ればできるきもしますが、、、

まあやりたいことが（トレロを見ても）わからなかったので何とも。。。

**Comment by hogehiga** [comment]
GPS.jsで取得した緯度経度でもって、Google マップへのリンク先のURLを書き換えればいけると思います（link_toは例えばダミーのURLにしておく）。
書き換え処理はsuccess関数あたりに仕込んでおけばよいかと。

**Comment by ta-ryo** [comment]
位置情報からGoogleMapへの遷移をする事ができました。
ありがとうございます。

**Comment by hogehiga** [comment]
:+1:
