### ISSUE TITLE
javascriptからRailsのControllerのActionを呼び出したいです。

### ISSUE THREAD

**Issue by ta-ryo** [East6/Board-Logger#66]
<img width="674" alt="screen shot 2018-12-11 at 13 19 04" src="https://user-images.githubusercontent.com/23465165/49778226-6f808880-fd47-11e8-8ebd-bdddd09cb5f7.png">
<img width="904" alt="screen shot 2018-12-11 at 13 18 53" src="https://user-images.githubusercontent.com/23465165/49778230-71e2e280-fd47-11e8-9b0a-4a8a303743e7.png">

**Comment by hogehiga** [comment]
ちょｗｗ

ソースを見ないとなんとも言えないので、まずはブランチをpushしてブランチ名を教えてください。
(master以外の)ブランチをpushしても、Herokuの本番環境には影響がないので、作業途中でも構いません。
というか、他のメンバーが作業内容を把握できるので、作業途中でもpushしたほうがいいです。

**Comment by ta-ryo** [comment]
12-11_GPSでpushしてます。伝えてなくてすいません。

**Comment by ta-ryo** [comment]
controllerとmodelは作成しただけでpushしてました。
書き忘れてます。

**Comment by hogehiga** [comment]
まず、JavaScriptは名前付き引数？に対応していません。
なので、`hogefunc(thing: "apple", price: 100)`のような書き方はできません。
`hogefunc("apple", 100)`のような形になります。

**Comment by hogehiga** [comment]
ただこの書き方だと、引数が増えたときに順番がわからなくなります。
例えば`hogefunc("apple", 100, "超うまい")`だったか、`hogefunc("apple", "超うまい", 100)`だったかどっちだっけ〜〜〜？といった感じです。

それを解消するためのテクニックとして、JavaScriptのオブジェクトを渡す方法があるようです。
例えば、`hogefunc({thing: "apple", price: 100, taste: "超うまい"})`のような形です。(波括弧がJavaScriptのオブジェクト(<https://developer.mozilla.org/ja/docs/Web/JavaScript/Guide/Working_with_Objects#Using_object_initializers>)を表すことに注意)。
JavaScriptのオブジェクトには、順序という概念がないようなので(参考: <https://stackoverflow.com/questions/5525795/does-javascript-guarantee-object-property-order>)、これでいい感じにやっていける、ということだと思います。

おそらく、あなたはこの書き方と混同していると思います。

**Comment by hogehiga** [comment]
あとは、`$.ajax`の仕様書が<http://api.jquery.com/jquery.ajax/>にあるので、それを読んでいけば、いい感じに、JavaScriptからURLへPOSTで切ると思います。
