### ISSUE TITLE
位置情報がうまく保存できません。

### ISSUE THREAD

**Issue by e165719** [East6/Board-Logger#74]
JavaScriptから位置情報を取ってくることができましたが、
それをBoardのモデルにうまく保存することができません。

Boardのモデルに新しくカラム(latitude, longitude)を追加したのですが、
JavaScriptへ飛ばした際に、locationやuser_idが取ってこれず、
ボード自体が保存できません。
locationとuser_idを取れるようにすればどうすればいいのでしょうか。

<img width="1044" alt="2018-12-17 17 48 07" src="https://user-images.githubusercontent.com/23465228/50076191-5d5d8900-0224-11e9-83e6-4ea05494df6b.png">

また、controllerからJavaScriptは呼ぶことができるのでしょうか。

ブランチはfeature/12-16_origin12-11_GPSです。
よろしくお願いします。

**Comment by hogehiga** [comment]
google mapを表示するために必要なAPIキーの設定方法が変わってるみたいなんですが。
環境変数の名前を変えるだけでいいんでしょうか……？
パッと見それでいい感じですが。

**Comment by hogehiga** [comment]
わかってないでいうのでアレなんですが、わざわざAjaxを用いてlat, lngを送信する必要はないのでは？
以下手順案です。

1. JavaScriptを使って、ユーザーに位置情報を教えてもらう(`navigator.geolocation.getCurrentPosition`)
1. 教えてもらった位置情報をformのhiddenに書き込む。<https://github.com/East6/Board-Logger/blob/b484839d303b0cded966b9b0655da778ab656f5c/app/views/boards/index.html.erb#L25> あたりがいいかと思われます。
1. 「+」ボタンを押すと、ボードの情報が位置情報込みでPOSTされるので、Railsのコントローラでいい感じにやっていく。

**Comment by e165719** [comment]
ご確認ありがとうございます。
問題を解決することができました。
