### ISSUE TITLE
位置情報取得の件です。

### ISSUE THREAD

**Issue by ta-ryo** [East6/Board-Logger#78]
![img_1237](https://user-images.githubusercontent.com/23465165/50135773-bb4ba880-02d8-11e9-9ca1-33e27e2f718f.PNG)

**Comment by hogehiga** [comment]
- どの画面でどのような操作をしたか
- 実際にはどうなったのか
- 本当はどうなってほしいのか

がないとエスパー以外無理かと思われ。

あとスマホ(safari)のログもほしいところですね。とり方は知りませんが。

**Comment by hogehiga** [comment]
あとはこのあたりが参考になるかもしれません。

https://github.com/East6/Board-Logger/issues/47

**Comment by hogehiga** [comment]
iOSのSafariのログ、この方法で取れるようです。

https://developer.apple.com/library/archive/documentation/AppleApplications/Conceptual/Safari_Developer_Guide/GettingStarted/GettingStarted.html

**Comment by hogehiga** [comment]
あとは、公式ドキュメントを参考にするのが良いです。

そもそもどのようなライブラリを使うにしろ、外部APIを使うにしろ、公式ドキュメントが、網羅性、正確性、速報性において最も優れているはずなんで、そっちを見たほうがいいです。
場所は<https://developers.google.com/maps/documentation/urls/guide#directions-action>です。

なんとなくですが、originを指定するとイケるかどうか試す価値があると思います。

**Comment by ta-ryo** [comment]
すいません。ありがとうございます。

**Comment by ta-ryo** [comment]
show画面のlink_toでgoogleMAPへのリンクを作っています。
実際にはリンクをクリックしたら現在位置を自動で取得できずにルート形成ができませんでした。
ほんとはリンクをクリックするだけで現在位置の情報を取得してルート形成をして欲しいです。

**Comment by hogehiga** [comment]
originを指定したら、iPad上でアプリにアクセスし、リンクをクリックするだけでルート形成ができました。

**Comment by hogehiga** [comment]
あとはアプリでGoogleMapへのリンクを作る際に、originをユーザーから取得した位置情報で書き換えてやれば良いと思います。

ただ、Safariだと、アプリにHTTPSでアクセスしないと、位置情報を送信してくれないようです(参考: <https://github.com/East6/Board-Logger/issues/47#issuecomment-441295087>)。

このアプリはPumaを使ってるようなので、PumaをHTTPSでのリクエストを受け付けるように設定すれば、ローカル開発時にも位置情報を取得できます。
設定のやり方はググれば出ると思います。

**Comment by East6** [comment]
ありがとうございます。
pumaの設定やってみます。
