### ISSUE TITLE
Androidで開くと表示がおかしくなる件について

### ISSUE THREAD

**Issue by East6** [East6/Board-Logger#82]

**Comment by East6** [comment]
iOSにCromeを入れてURLを開いたやつです。
![img_4891](https://user-images.githubusercontent.com/23465219/50240296-bd605500-0407-11e9-85f9-dc7c252db9c4.PNG)

**Comment by hogehiga** [comment]
あとは、最近のブラウザだとフォントサイズの指定にはvminというのが使えます。
これは、viewportの幅が小さい方に対する割合を100分率で指定できます。
viewportに基づいて計算されるので、これを使えば、スクリーン幅ごとにスタイルシートを用いる必要がなくなるかと思います。

#### 参考
- <https://developer.mozilla.org/ja/docs/Web/CSS/@viewport>
- <https://developer.mozilla.org/ja/docs/Glossary/viewport>
- <https://developer.mozilla.org/ja/docs/Web/CSS/Length>

**Comment by East6** [comment]
ありがとうございます。
viewport を参考にしながら，変更してみます。

**Comment by East6** [comment]
application.scss の 「zoom」が非標準で，それが原因ぽかったです。
zoomを，コメントアウトすると
　iPhone と Android が同じ表示になりました。

意見をいただいた，viewport で調整しました。
ありがとうございました。
